### ISSUE TITLE
Modularize jsQUEST & numeric.js

### ISSUE THREAD

**Issue by tpronk** [kurokida/jsQUEST#1]
Hey @kurokida,

Continuing one of the topics that came up in our chat on the [PsychoPy forum](https://discourse.psychopy.org/t/jsquest-a-bayesian-adaptive-psychometric-method-for-measuring-thresholds-in-online-experiments/23115): how to turn jsQUEST into a module (and have it play nice with numeric.js)? 

An advantage of numeric.js not being developed anymore is that we can edit its structure without worrying what happens upstream. I'm quite sure I can help you out converting it into a module, but before we go do that, a question...

What kind of module would you like? If I may make a recommendation: ES6 is the most modern standard. A build chain could look a bit like this:
* At PsychoJS we use [babel](https://babeljs.io/) to compile ES6 into JavaScript that is suitable for older browsers. 
* Probably babel can also export ES6 to a global variable, similar to what you've got now, but for sure this can be done with browsersify, as I did in [this experiment](https://gitlab.pavlovia.org/tpronk/demo_embed_html).

Note that I'm not really an expert in build chains, but we've got an expert in our team; I'll pull him in once we've got an outline of our plan.

Best, Thomas

**Comment by kurokida** [comment]
Thank you for creating this thread.

I don't know much about modularization.
Do you mean that by using the babel the numeric.js can be converted to a module, and I have to select one of the ways to do that?
To be honest, I am not sure which choice is the best for me, and I've never used babel, browsersify, and Node.js before.

After I read your post, I tried to use the browsersify for the first time, and successfully run the following code you suggested.

```
browserify index.js --s flat -o flat-5.0.0.js
```

Probably, I can use the browsersify.

I have a question about the browsersify.
I notice that using the browsersify I seem to be able to make the jsQUEST module without making numeric.js module.
Am I right?

**Comment by kurokida** [comment]
The problem remains, but I've made some progress and will write about it.

I added this code at the bottom of the numeric.js.
```javascript
module.exports = numeric;
```

Then, I created a new js (test1.js) file that looks like this:

```javascript
const numeric = require("./numeric-module");
console.log(numeric.linspace(1,5))
console.log(numeric.mul(2,3))
```

Then,

```
browserify test1.js -o test1-app.js
```

The test1-app workds fine.

Next, I added the following line at the top of jsQUEST.js.

```javascript
const numeric = require("./numeric-module");
```

Then,

```
browserify jsQUEST.js -o app.js
```

There is no error message.

I added this line in the jsQuestDemo.html

```javascript
<script src="./app.js"></script>
```

The Chrome JavaScript console outputs this error message.

Uncaught ReferenceError: QuestCreate is not defined at jsQuestDemo.html:28

**Comment by tpronk** [comment]
Let's have some fun! :)

Could you make a branch in your repo for these changes? Then I can fetch those on my side and reproduce the error you report.

**Comment by kurokida** [comment]
Thank you for your reply.

I'm slowly gaining a better understanding of JavaScript module.

I created a new branch named modularize.

Please see test2.js.

In the test2.js, the numeric functions work fine.

Then I have succeeded to export QuestCreate function, but the following error appeared
`interp1 is not defined`

I know the reason. I don't import the inter1 function.

https://www.npmjs.com/package/interp1
From this page, it seems that interp1 supports ES6 modules.

I don't know how to import the interp1 using browserify, although I could install the interp1 using the npm command.

The bigger problem is that even if the test2 works properly, this is not what I want to do.

The test2 shows that users of jsQUEST must use also browserify and node.js, and the import style is different from that of PsychoJS.

I think the style of test2 is CommonJS and the style of PsychoJS is ES6 module, am I understanding correctly?

**Comment by tpronk** [comment]
Thanks! I took the liberty of making a fork & branch of jsQUEST that acts like an ES6 module. It imports interp1 and a fork of numeric (which I adapted to be an ES6 module as well). To check if everything works I added a demo and a test: https://github.com/tpronk/jsQUEST/tree/modularize_es6

Note that the repo doesn't include the code for interp1 nor numeric; those are in seperate repos, but they get pulled in when you install this fork&branch of the jsQUEST repo.

To make it work the same way as it used to (via global variables), we can make different builds of jsQUEST. Such a build would contain both jsQUEST and the two libraries it depends on in a single JS file. I'll need to ask around a bit to find out whether browserify or babel (or something else) is the nicest approach here.

BTW, no worries if this approach doesn't appeal to you. It's nice for PsychoJS since it works well in our system, but if you prefer the approach you take now, don't feel obliged to adapt the ES6 approach. I built my fork & branch such that the conversion to ES6 is done with as little modification to your code as possible (only some imports at the top and an export at the bottom), so I could easily update it with any changes you make.

**Comment by tpronk** [comment]
I got some input on how to build the library. The current version of `modularize_es6` includes [rollup](https://rollupjs.org) as a dev-dependency (that means it's only needed to develop the library, not when using the library). In `dist/` there is a bundle file that can be treated like a global or imported in CommonJS style. I added a slightly modified version of your demo to show how it works.

There is one important change with how it used to work: inside of the demo, each jsQUEST function is part of a global object `jsQUEST`, so instead of writing `QuestQuantile(q); ` you need to write `jsQUEST.QuestQuantile(q);`. When bundling, the name of this global object can be specified at [this line](https://github.com/tpronk/jsQUEST/blob/e2c6e4e32f5b2870ae7eb5add257b12bb01471f2/rollup.config.js#L8).

**Comment by kurokida** [comment]
Thank you very much for your cooperation.

I tried to install the new jsQUEST according to [the readme](https://github.com/tpronk/jsQUEST/tree/modularize_es6).
Your jsQUEST works fine. I was impressed!
But I have a question.

When I run the `rollup -c`, I got an error that the command "rollup" does not exist.

Do I have to install rollup manually using `npm install rollup`?

**Comment by tpronk** [comment]
Happy you like it!

I just redid an `npm install`, and on my side that set everything up correctly for `rollup -c`. You can verify that rollup is there in your node_modules folder. For instance, on my Windows 10 computer I got a folder over here...

`C:\GITHUB\misc\tpronk.jsQUEST\node_modules\@rollup`

I have noticed that sometimes calling `rollup` from the command line doesn't work on other Operating Systems, especially Linux. A question and a suggestion:
- Which OS are you using?
- Try `npx rollup -c` (that's how I managed to solve comparable problems when running a build via Github Actions)

**Comment by kurokida** [comment]
Thank you for your reply.

I am using Windows 10 Home edition.

Then, I can run the npx command successfully.
These are output messages.

`npx rollup -c`

src/jsQUEST.js → dist...
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules\numeric_es6\src\numeric.js
2011:     var k,A,B,C;
2012:     for(k in numeric.ops2) {
2013:         if(isFinite(eval('1'+numeric.ops2[k]+'0'))) A = '[Y[0],Y[1],numeric.'+k+'(X,Y[2])]';
                          ^
2014:         else A = 'NaN';
2015:         if(isFinite(eval('0'+numeric.ops2[k]+'1'))) B = '[X[0],X[1],numeric.'+k+'(X[2],Y)]';
...and 3 other occurrences
created dist in 570ms

I can get a new jsQUEST in the dist folder. Thank you for your suggestions.
I'm going to ignore the error messages about `eval` for now.

**Comment by tpronk** [comment]
Nice that this fixed it. Yeah, rollup does some checks on the code, but
indeed, that's for later concern.

**Comment by kurokida** [comment]
I'm currently considering changing my jsQUEST repository to publish both a module for PsychoPy and as a bundle for jsPsych.
But I don't know exactly how.

One idea is that I receive a pull request from you.

Another idea is to copy package.json and rollup.config.js from your repository to mine, and run the rollup command in my repo.

Which method do you think is better?

Then I'll send you a message on twitter. Could you check there as well?

**Comment by tpronk** [comment]
Sorry for the late reply; had a brief vacation.

I'd recommend a pull request; it has the advantage that the history of my edits gets merged with yours, so later on we can easily see what happened when. Shall I make one?

**Comment by kurokida** [comment]
If you could send me a pull request, it would be greatly appreciated!

By the way, I remembered that I had sent a merge request before. Please check
https://gitlab.pavlovia.org/tpronk/demo_jsquest/merge_requests
, too.

**Comment by tpronk** [comment]
My pleasure! I just made the PR. Also, sorry for missing the merge request on gitlab. I just replied over there.
