### ISSUE TITLE
An intensity that was in range was reported as out of range

### ISSUE THREAD

**Issue by tpronk** [kurokida/jsQUEST#13]
Denis Pelli has been running tests of the PsychoJS integration of jsQUEST and got an [unexpected error message](https://discourse.psychopy.org/t/incoherent-error-message-from-questhandler-in-psychojs/25864):
```
QuestUpdate: intensity -2.1941879156398305 out of range
-2.1989700043360187 to 2.8010299956639813. Pdf will be inexact.
Suggest that you increase “range” in call to QuestCreate.
```

**Comment by kurokida** [comment]
Thank you for contacting me.
I have replied in [the topic](https://discourse.psychopy.org/t/incoherent-error-message-from-questhandler-in-psychojs/25864).

I have an additional report.

When I run the test/jsQUEST_test.js using v1.01 which includes the bug, I received the following output.

> The results of jsQUEST, MATLAB, and PsychoPy should be almost equal.
jsQUEST: Final threshold estimate (mean+-sd) is 79.04674452884068 +- 4.182374537623455
MATLAB: Final threshold estimate (mean+-sd) is 79.073768 +- 4.173877
PsychoPy: Final threshold estimate (mean+-sd) is 79.33662751283129 +- 4.233607966057011

After fixing the bug, I received the following output.

> The results of jsQUEST, MATLAB, and PsychoPy should be almost equal.
jsQUEST: Final threshold estimate (mean+-sd) is **79.07376848839164 +- 4.173877227129627**
MATLAB: Final threshold estimate (mean+-sd) is **79.073768 +- 4.173877**
PsychoPy: Final threshold estimate (mean+-sd) is 79.33662751283129 +- 4.233607966057011

The results of jsQUEST and MATLAB are now even closer together.

**Comment by tpronk** [comment]
Nice! Here is an idea on version numbers. Maybe consider adopting semver?
That way the version number communicates whether a new release is a bug
fix, adds a new feature,or is a breaking change in the API. See
https://devhints.io/semver

**Comment by kurokida** [comment]
Thank you for your advice.

Let me confirm.
Does it mean that I should have released 1.0.2 instead of 1.1?

I agree with it. I hadn't really thought about this.
Since I have already released version 1.1, how about we follow semver from the next version?

**Comment by tpronk** [comment]
Yeah, the bugfix would increase the last number of the version. And agreed,
let's follow this convention for future updates

**Comment by kurokida** [comment]
Thank you for your reply. I understand.
