### ISSUE TITLE
Working with lab.js

### ISSUE THREAD

**Issue by kurokida** [kurokida/jsQUEST#8]
Hi @tpronk , I'm sorry for bothering you.

You mentioned that you've used lab.js before, so let me ask you some questions.

This is a jsQUEST sample program for lab.js.
[jsQuest_lab_js_json.txt](https://github.com/kurokida/jsQUEST/files/6691270/jsQuest_lab_js_json.txt)
Change the extension to json and try to load it in lab.js.

You'll see intensity columns jsQUEST calculated in the output (CSV) file. In other words, jsQUEST is working fine.

I also want to present the intensity values on the Screen1 or Screen2 using a text `${this.parameters.intensity}`, but I couldn't.

Do you have any suggestions?

**Comment by tpronk** [comment]
Let's ask in their Slack group? https://slackin-numbercrunchers.herokuapp.com/

**Comment by kurokida** [comment]
I've asked a question on the Slack group. I've also noticed a reaction from you. Thank you!
